#!/usr/bin/env python3
"""Regenerate sitemap.xml from the router's own route table.

Why this exists: the routes are declared once, in the ROUTES array and MODULES
map inside index.html. Writing them out again by hand in sitemap.xml means the
two drift the first time a route is added. This reads them back out of the page.

Only run it once the site is served with 200s for app routes (see _redirects).
On GitHub Pages those paths answer 404, and a sitemap full of 404s just fills
Search Console with errors.

    python3 tools/build-sitemap.py            # writes sitemap.xml
    python3 tools/build-sitemap.py --check    # list routes, write nothing
"""
import json, re, sys, datetime, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
HTML = ROOT / "index.html"
BASE = "https://bioinfocodex.com"

# priority / changefreq by route; anything unlisted falls back to the default
WEIGHT = {
    "/":                 ("1.0", "weekly"),
    "/tools":            ("0.9", "weekly"),
    "/learn":            ("0.9", "weekly"),
    "/tools/rnaflow":    ("0.9", "monthly"),
    "/tools/genenet":    ("0.8", "monthly"),
    "/download":         ("0.8", "monthly"),
    "/resources":        ("0.7", "monthly"),
    "/contact":          ("0.5", "yearly"),
}
DEFAULT = ("0.5", "monthly")


def routes_from_page(html: str):
    paths = re.findall(r"\{\s*path:\s*'([^']+)'", html)
    if not paths:
        sys.exit("No ROUTES found in index.html — has the router changed shape?")
    block = re.search(r"const MODULES = \{(.*?)\};", html, re.S)
    slugs = re.findall(r"'([a-z-]+)'\s*:\s*'mod\d+'", block.group(1)) if block else []
    return paths + [f"/learn/{s}" for s in slugs]


def main():
    html = HTML.read_text(encoding="utf-8")
    paths = routes_from_page(html)
    today = datetime.date.today().isoformat()

    if "--check" in sys.argv:
        for p in paths:
            print(f"  {p}")
        print(f"\n  {len(paths)} routes")
        return

    out = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<!-- Generated by tools/build-sitemap.py from the ROUTES table in",
        "     index.html. Do not hand-edit; re-run the script instead. -->",
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ]
    for p in paths:
        pri, freq = WEIGHT.get(p, DEFAULT)
        out += ["  <url>",
                f"    <loc>{BASE}{p}</loc>",
                f"    <lastmod>{today}</lastmod>",
                f"    <changefreq>{freq}</changefreq>",
                f"    <priority>{pri}</priority>",
                "  </url>"]
    out.append("</urlset>")
    (ROOT / "sitemap.xml").write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"  sitemap.xml written with {len(paths)} URLs")


if __name__ == "__main__":
    main()
